"""Well-known dependency registries.

Leaf module -- imports nothing from siblings to avoid circular imports.
All sets are frozensets for O(1) membership testing.
Normalized variants strip hyphens, underscores, and lowercase for
language-insensitive matching.

ASCII-only. Python 3.8+ compatible.
"""

# ---------------------------------------------------------------------------
# Raw well-known sets (exact canonical names)
# ---------------------------------------------------------------------------

PYTHON_WELL_KNOWN = frozenset(
    [
        "flask",
        "django",
        "fastapi",
        "sqlalchemy",
        "alembic",
        "celery",
        "redis",
        "pymongo",
        "motor",
        "psycopg2",
        "aiohttp",
        "httpx",
        "requests",
        "urllib3",
        "boto3",
        "botocore",
        "pydantic",
        "marshmallow",
        "pytest",
        "unittest",
        "mock",
        "coverage",
        "mypy",
        "pylint",
        "flake8",
        "black",
        "isort",
        "setuptools",
        "wheel",
        "pip",
        "virtualenv",
        "numpy",
        "pandas",
        "scipy",
        "matplotlib",
        "sklearn",
        "tensorflow",
        "torch",
        "keras",
        "transformers",
        "langchain",
        "langgraph",
        "anthropic",
        "loguru",
        "structlog",
        "python-dotenv",
        "pydantic-settings",
        "uvicorn",
        "gunicorn",
        "starlette",
        "typer",
        "click",
        "rich",
        "jinja2",
        "werkzeug",
        "itsdangerous",
        "markupsafe",
        "cryptography",
        "paramiko",
        "fabric",
        "ansible",
        "docker",
        "kubernetes",
        "boto",
        "google-cloud",
        "azure",
        "stripe",
        "twilio",
        "sendgrid",
        "pillow",
        "lxml",
        "beautifulsoup4",
        "scrapy",
        "selenium",
        "playwright",
        "sqlmodel",
        "tortoise-orm",
        "databases",
        "aiosqlite",
        "aiomysql",
        "asyncpg",
        "influxdb",
        "elasticsearch",
        "pinecone",
        "mcp",
        "fastmcp",
        "httpcore",
        "certifi",
        "charset-normalizer",
        "packaging",
        "tomli",
        "tomllib",
        "yaml",
        "pyyaml",
        "toml",
    ]
)

JAVA_WELL_KNOWN = frozenset(
    [
        "org.springframework",
        "org.hibernate",
        "org.apache",
        "com.google",
        "com.fasterxml.jackson",
        "junit",
        "org.mockito",
        "org.slf4j",
        "ch.qos.logback",
        "log4j",
        "commons-lang",
        "commons-io",
        "commons-collections",
        "guava",
        "lombok",
        "javax",
        "jakarta",
        "io.micronaut",
        "io.quarkus",
        "org.projectlombok",
        "net.sf",
        "org.bouncycastle",
        "io.netty",
        "com.squareup",
        "okhttp3",
        "retrofit2",
        "com.zaxxer",
        "mysql",
        "postgresql",
        "h2database",
        "flyway",
        "liquibase",
        "mapstruct",
        "modelmapper",
    ]
)

NODE_WELL_KNOWN = frozenset(
    [
        "express",
        "koa",
        "hapi",
        "fastify",
        "nest",
        "next",
        "nuxt",
        "react",
        "vue",
        "angular",
        "svelte",
        "webpack",
        "vite",
        "rollup",
        "babel",
        "typescript",
        "eslint",
        "prettier",
        "jest",
        "mocha",
        "chai",
        "sinon",
        "supertest",
        "axios",
        "got",
        "node-fetch",
        "lodash",
        "ramda",
        "moment",
        "dayjs",
        "date-fns",
        "uuid",
        "bcrypt",
        "jsonwebtoken",
        "passport",
        "helmet",
        "cors",
        "morgan",
        "body-parser",
        "multer",
        "sharp",
        "jimp",
        "socket.io",
        "ws",
        "mongoose",
        "sequelize",
        "typeorm",
        "prisma",
        "knex",
        "objection",
        "redis",
        "ioredis",
        "amqplib",
        "kafkajs",
        "dotenv",
        "yargs",
        "commander",
        "chalk",
        "ora",
        "inquirer",
        "nodemon",
        "pm2",
    ]
)

GO_WELL_KNOWN = frozenset(
    [
        "github.com/gin-gonic",
        "github.com/gorilla",
        "github.com/labstack",
        "github.com/go-chi",
        "github.com/stretchr",
        "github.com/sirupsen",
        "go.uber.org",
        "github.com/pkg/errors",
        "github.com/spf13",
        "github.com/google",
        "google.golang.org",
        "golang.org/x",
    ]
)

RUST_WELL_KNOWN = frozenset(
    [
        "serde",
        "tokio",
        "actix-web",
        "axum",
        "warp",
        "rocket",
        "reqwest",
        "hyper",
        "tonic",
        "prost",
        "diesel",
        "sqlx",
        "anyhow",
        "thiserror",
        "log",
        "tracing",
        "clap",
        "structopt",
        "chrono",
        "uuid",
        "rand",
        "regex",
        "rayon",
        "crossbeam",
    ]
)

# ---------------------------------------------------------------------------
# Normalized variants: strip hyphens, underscores, lowercase
# Used for O(1) fuzzy membership checks in _classify_dep
# ---------------------------------------------------------------------------

PYTHON_WELL_KNOWN_NORMALIZED = frozenset(n.replace("-", "").replace("_", "").lower() for n in PYTHON_WELL_KNOWN)

JAVA_WELL_KNOWN_NORMALIZED = frozenset(n.replace("-", "").replace("_", "").lower() for n in JAVA_WELL_KNOWN)

NODE_WELL_KNOWN_NORMALIZED = frozenset(n.replace("-", "").replace("_", "").lower() for n in NODE_WELL_KNOWN)

GO_WELL_KNOWN_NORMALIZED = frozenset(n.replace("-", "").replace("_", "").lower() for n in GO_WELL_KNOWN)

RUST_WELL_KNOWN_NORMALIZED = frozenset(n.replace("-", "").replace("_", "").lower() for n in RUST_WELL_KNOWN)
