#!/usr/bin/env python3
"""
Check Latest Recommendations - Quick command to see auto-generated recommendations

Usage:
    python check-recommendations.py [--json]

Shows the latest recommendations generated by auto-recommendation-daemon
"""

import sys
import json
from pathlib import Path
from datetime import datetime

MEMORY_DIR = Path.home() / ".claude" / "memory"
RECOMMENDATIONS_FILE = MEMORY_DIR / ".latest-recommendations.json"

# Colors
GREEN = '\033[92m'
YELLOW = '\033[93m'
RED = '\033[91m'
BLUE = '\033[94m'
CYAN = '\033[96m'
RESET = '\033[0m'
BOLD = '\033[1m'

def format_time_ago(timestamp_str):
    """Format timestamp as 'X minutes ago'"""
    try:
        ts = datetime.fromisoformat(timestamp_str)
        now = datetime.now()
        diff = now - ts

        seconds = diff.total_seconds()
        if seconds < 60:
            return f"{int(seconds)} seconds ago"
        elif seconds < 3600:
            return f"{int(seconds/60)} minutes ago"
        elif seconds < 86400:
            return f"{int(seconds/3600)} hours ago"
        else:
            return f"{int(seconds/86400)} days ago"
    except:
        return timestamp_str

def main():
    json_output = '--json' in sys.argv

    if not RECOMMENDATIONS_FILE.exists():
        if json_output:
            print(json.dumps({"error": "No recommendations available"}))
        else:
            print(f"{YELLOW}No recommendations available yet{RESET}")
            print(f"\nStart the auto-recommendation daemon:")
            print(f"  python ~/.claude/memory/auto-recommendation-daemon.py --start")
        return 1

    try:
        with open(RECOMMENDATIONS_FILE, 'r') as f:
            data = json.load(f)

        if json_output:
            print(json.dumps(data, indent=2))
            return 0

        # Pretty display
        print(f"\n{BOLD}{'='*60}{RESET}")
        print(f"{BOLD}{GREEN}LATEST RECOMMENDATIONS{RESET}")
        print(f"{BOLD}{'='*60}{RESET}\n")

        # Timestamp
        if 'timestamp' in data:
            time_ago = format_time_ago(data['timestamp'])
            print(f"{BOLD}Generated:{RESET} {time_ago}")
            print()

        # Model
        if 'model' in data:
            model = data['model']
            model_name = model.get('recommended', 'N/A').upper()
            reason = model.get('reason', '')
            confidence = model.get('confidence', 0)

            if model_name == 'HAIKU':
                color = GREEN
            elif model_name == 'OPUS':
                color = CYAN
            else:
                color = BLUE

            print(f"{BOLD}MODEL:{RESET} {color}{model_name}{RESET}")
            print(f"  Reason: {reason}")
            print(f"  Confidence: {confidence:.0%}")
            print()

        # Context
        if 'context' in data:
            context = data['context']
            status = context.get('status', 'unknown').upper()
            percentage = context.get('percentage', 0)

            if status == 'CRITICAL':
                color = RED
            elif status == 'WARNING':
                color = YELLOW
            else:
                color = GREEN

            print(f"{BOLD}CONTEXT:{RESET} {color}{status}{RESET} ({percentage:.1f}%)")
            print()

        # Skills
        if 'skills' in data and data['skills']:
            print(f"{BOLD}SKILLS ({len(data['skills'])}){RESET}:")
            for skill in data['skills']:
                print(f"  -> {CYAN}{skill}{RESET}")
            print()

        # Agents
        if 'agents' in data and data['agents']:
            print(f"{BOLD}AGENTS ({len(data['agents'])}){RESET}:")
            for agent in data['agents']:
                print(f"  -> {BLUE}{agent}{RESET}")
            print()

        # Optimizations
        if 'optimizations' in data and data['optimizations']:
            print(f"{BOLD}OPTIMIZATIONS ({len(data['optimizations'])}){RESET}:")
            for opt in data['optimizations']:
                print(f"  [OK] {opt}")
            print()

        # Warnings
        if 'warnings' in data and data['warnings']:
            print(f"{BOLD}{RED}WARNINGS ({len(data['warnings'])}){RESET}:")
            for warning in data['warnings']:
                print(f"  {RED}[!]{RESET} {warning}")
            print()

        # Actions
        if 'actions' in data and data['actions']:
            print(f"{BOLD}ACTION CHECKLIST{RESET}:")
            for action in data['actions']:
                print(f"  {action}")
            print()

        print(f"{BOLD}{'='*60}{RESET}\n")

        return 0

    except Exception as e:
        if json_output:
            print(json.dumps({"error": str(e)}))
        else:
            print(f"{RED}ERROR: Failed to read recommendations: {e}{RESET}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
