"""
pin_requirements.py - Pin project dependencies to exact and bounded versions.

Reads requirements.txt, queries pip for the currently installed version of
each package, and writes two output files:

  requirements.pinned.txt  -- exact pins (package==X.Y.Z)
  requirements.bounds.txt  -- bounded ranges (package>=X.Y.Z,<X+1.0.0)

Usage:
  python scripts/pin_requirements.py
  python scripts/pin_requirements.py --output-dir dist/

Python 3.8+ compatible. ASCII-only (cp1252-safe for Windows).
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REQUIREMENTS_FILE = "requirements.txt"
PINNED_OUTPUT = "requirements.pinned.txt"
BOUNDS_OUTPUT = "requirements.bounds.txt"

# Regex: captures the package name from a requirement line.
# Handles: name, name==x, name>=x, name[extra], name @ url
_PACKAGE_NAME_RE = re.compile(r"^([A-Za-z0-9_.-]+)", re.ASCII)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def parse_package_names(req_lines):
    # type: (list) -> list
    """Return bare package names from requirements lines.

    Skips blank lines, comments, and options (lines starting with '-').
    """
    names = []
    for line in req_lines:
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue
        # Strip inline comments
        line = line.split("#")[0].strip()
        if not line:
            continue
        m = _PACKAGE_NAME_RE.match(line)
        if m:
            names.append(m.group(1))
    return names


def get_installed_version(package_name):
    # type: (str) -> str
    """Return the installed version string for package_name using pip show.

    Returns empty string if the package is not installed or pip fails.
    """
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "show", package_name],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            return ""
        for line in result.stdout.splitlines():
            if line.startswith("Version:"):
                return line.split(":", 1)[1].strip()
    except (subprocess.TimeoutExpired, OSError):
        pass
    return ""


def make_bounded_version(version):
    # type: (str) -> str
    """Derive a bounded specifier from an exact version string.

    Strategy: pin to >= current major.minor, < next major version.

    Examples:
      2.1.1  ->  >=2.1.1,<3.0.0
      0.7.2  ->  >=0.7.2,<1.0.0
      1.0    ->  >=1.0,<2.0.0
    """
    parts = version.split(".")
    try:
        major = int(parts[0])
        next_major = major + 1
    except (ValueError, IndexError):
        # Cannot parse major version - fall back to exact pin
        return "==" + version
    return ">={version},<{next_major}.0.0".format(version=version, next_major=next_major)


def build_header(source_file):
    # type: (str) -> str
    """Return a comment header for generated files."""
    return (
        "# Auto-generated by scripts/pin_requirements.py\n"
        "# Source: {source}\n"
        "# Do not edit manually - re-run pin_requirements.py to regenerate.\n"
        "#\n"
    ).format(source=source_file)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(output_dir=None):
    # type: (str) -> int
    """Pin requirements and write output files.

    Returns 0 on success, 1 on error.
    """
    req_path = Path(REQUIREMENTS_FILE)
    if not req_path.exists():
        print("ERROR: {path} not found. Run from project root.".format(path=req_path))
        return 1

    req_lines = req_path.read_text(encoding="utf-8").splitlines()
    packages = parse_package_names(req_lines)

    if not packages:
        print("WARNING: No packages found in {path}.".format(path=req_path))
        return 0

    print("Querying pip for {n} packages...".format(n=len(packages)))

    pinned_lines = []
    bounds_lines = []
    missing = []

    for pkg in packages:
        version = get_installed_version(pkg)
        if version:
            pinned_lines.append("{pkg}=={version}".format(pkg=pkg, version=version))
            bounded = make_bounded_version(version)
            bounds_lines.append("{pkg}{spec}".format(pkg=pkg, spec=bounded))
            print("  OK  {pkg}=={version}".format(pkg=pkg, version=version))
        else:
            pinned_lines.append("# NOT INSTALLED: {pkg}".format(pkg=pkg))
            bounds_lines.append("# NOT INSTALLED: {pkg}".format(pkg=pkg))
            missing.append(pkg)
            print("  MISS {pkg} (not installed)".format(pkg=pkg))

    # Determine output directory
    if output_dir:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
    else:
        out_dir = Path(".")

    header = build_header(str(req_path))

    pinned_path = out_dir / PINNED_OUTPUT
    pinned_path.write_text(
        header + "\n".join(pinned_lines) + "\n",
        encoding="utf-8",
    )
    print("\nWrote: {path}".format(path=pinned_path))

    bounds_path = out_dir / BOUNDS_OUTPUT
    bounds_path.write_text(
        header + "\n".join(bounds_lines) + "\n",
        encoding="utf-8",
    )
    print("Wrote: {path}".format(path=bounds_path))

    if missing:
        print("\nWARNING: {n} package(s) not installed: {pkgs}".format(n=len(missing), pkgs=", ".join(missing)))
        print("Install them with: pip install -r {path}".format(path=req_path))

    print("\nDone. {total} packages processed, {miss} missing.".format(total=len(packages), miss=len(missing)))
    return 0


def _parse_args(argv=None):
    # type: (list) -> argparse.Namespace
    parser = argparse.ArgumentParser(
        description=(
            "Pin requirements.txt to exact versions (requirements.pinned.txt) "
            "and bounded ranges (requirements.bounds.txt)."
        )
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        metavar="DIR",
        help="Directory for output files (default: current directory).",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = _parse_args()
    sys.exit(main(output_dir=args.output_dir))
